# Generated by Django 5.0 on 2023-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy1web', '0002_bibik_ocena1na10_bibik_pseudonim'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibik',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
